# Generated by Django 5.0.6 on 2024-06-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type'),
        ('transactions', '0003_remove_transaction_recipient_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sender', to='accounts.userbankaccount'),
        ),
    ]
