# Generated by Django 5.0.6 on 2024-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Sent'), (4, 'Received'), (5, 'Loan Request'), (6, 'Loan Repay')], null=True),
        ),
    ]
